name: Latest medium blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '30 13 */30 * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest medium blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@shreyashshetty"
